# Week 1 Checkpoint

## Retail Sales Forecasting Project

### Completed Tasks
- Day 1: Dataset Selection & EDA
- Day 2: Data Cleaning & Feature Engineering
- Day 3: Customer Segmentation (K-Means & DBSCAN)
- Day 4: Time Series Data Preparation
- Day 5: Prophet Baseline Model
- Day 6: LSTM Model

Week 1 tasks completed successfully.

In [17]:
import pandas as pd

In [18]:
import os
os.listdir()

['Day_7.ipynb', 'Untitled.ipynb', 'README.md', 'data', 'notebooks']

In [19]:
import os
os.listdir("notebooks")

['Day_1 .ipynb',
 'Day_2.ipynb',
 'Day_5.ipynb',
 'Intro.ipynb',
 'Year_2009_2010_Cleaned.csv',
 'Year_2010_2011_Cleaned.csv',
 'day6.ipynb',
 'day_3.ipynb',
 'day_4_.ipynb',
 'sqlite.ipynb',
 'cpp-tiny-ray-tracer.ipynb',
 'Lorenz.ipynb',
 'cpp.ipynb',
 'r.ipynb',
 'cpp-third-party-libs.ipynb']

In [20]:
import pandas as pd

df = pd.read_csv("notebooks/Year_2010_2011_Cleaned.csv")

In [21]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Customer_Segment,Sales_Channel,Payment_Mode,Order_Priority,Unnamed: 12
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 8.26,2.55,17850.0,United Kingdom,NaN,Regular,Online,UPI,High
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 8.26,3.39,17850.0,United Kingdom,NaN,Regular,Online,UPI,Low
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 8.26,2.75,17850.0,United Kingdom,NaN,Premium,Offline,Card,Medium
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 8.26,3.39,17850.0,United Kingdom,NaN,New,Retail,Cash,Low
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 8.26,3.39,17850.0,United Kingdom,NaN,Regular,Online,Net Banking,High

In [22]:
df.shape

(541910, 13)

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Invoice           541910 non-null  str
 1   StockCode         541910 non-null  str
 2   Description       540456 non-null  str
 3   Quantity          541910 non-null  int64
 4   InvoiceDate       541910 non-null  str
 5   Price             541910 non-null  float64
 6   Customer ID       406830 non-null  float64
 7   Country           541910 non-null  str
 8   Customer_Segment  0 non-null       float64
 9   Sales_Channel     541869 non-null  str
 10  Payment_Mode      541869 non-null  str
 11  Order_Priority    541869 non-null  str
 12  Unnamed: 12       541869 non-null  str
dtypes: float64(3), int64(1), str(9)
memory usage: 35.1 MB

In [24]:
df.describe()

            Quantity          Price    Customer ID  Customer_Segment
count  541910.000000  541910.000000  406830.000000               0.0
mean        9.552234       4.611138   15287.684160               NaN
std       218.080957      96.759765    1713.603074               NaN
min    -80995.000000  -11062.060000   12346.000000               NaN
25%         1.000000       1.250000   13953.000000               NaN
50%         3.000000       2.080000   15152.000000               NaN
75%        10.000000       4.130000   16791.000000               NaN
max     80995.000000   38970.000000   18287.000000               NaN

In [25]:
df.isnull().sum()

Invoice                  0
StockCode                0
Description           1454
Quantity                 0
InvoiceDate              0
Price                    0
Customer ID         135080
Country                  0
Customer_Segment    541910
Sales_Channel           41
Payment_Mode            41
Order_Priority          41
Unnamed: 12             41
dtype: int64

# Week 1 Checkpoint Summary

## Completed Deliverables

- EDA Report Completed
- Cleaned Dataset Prepared
- Customer Segmentation Completed
- Time Series Preparation Completed
- Prophet Baseline Model Completed
- LSTM Model Completed

All Week 1 tasks have been completed successfully.